root: ./data
output: ./output
type: submission
mode: offline

train:
  file: train.csv
  dep_vars: ["Class"]
  drop_vars: []
  val_split: 0.2
  sampling_strategy: smote

test:
  file: test.csv

classifier:
  name: xgboost
  type: xgboost
  kfold_kwargs:
    n_splits: 7
    n_repeats: 4
  model_kwargs:
    objective: binary:logistic
    colsample_bylevel: 0.3
    colsample_bynode: 0.7
    colsample_bytree: 1.0
    gamma: 0.6
    learning_rate: 0.03
    max_depth: 3
    min_child_weight: 0.5
    n_estimators: 650
    reg_alpha: 0.0
    reg_lambda: 0.0
    scale_pos_weight: 5.5
    subsample: 0.6
    tree_method: hist

batch_size: 128
